# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12d37caa09ecbe63bdc29a6cbf7e53023d768d4c67f26e3813e9c9f8cea9e1e8236792a5961cad03c8b9104469ee8c65bad5b2421c1f10b641de816f6eeb159f

test:
  secret_key_base: 35cdcaddad96056bd5a78f0e6797ce7caa43a05dc2f3665a10e8918231d2ebc237d47622dfd3f6a04490bc8cd09e8ffc4a3554608b8ea30decdf662084f846be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
